version: '3'
services:

  apache:
    container_name: myapache
    image: httpd:2.4.33-alpine
    ports:
      - 8080:80
    volumes:
      - ./webdir:/usr/local/apache2/htdocs/

  node:
    container_name: mynode
    image: node:8.11.1-alpine
    ports:
      - 8000:8000
    working_dir: /home/node/app
    volumes:
      - ./keijiban-api:/home/node/app
    links:
      - postgres:postgres
    environment:
      - DB_HOST=postgres
    command: npm run installStart

  postgres:
    container_name: mypostgres
    image: postgres:10.3-alpine
    volumes:
      - ./data:/var/lib/postgresql/data
