openapi: 3.0.0
info:
  title: Keijiban
  version: v2
paths:
  /contoribution:
    get:
      summary: 全投稿内容表示
      responses:
        '200':
          description: 過去投稿された内容の一覧
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContributionList'
components:
  schemas:
    Contribution:
      required:
        - id
        - contributor
        - body
        - createdate
      properties:
        id:
          type: integer
          format: int32
        contributor:
          type: string
        body:
          type: string
        createdate:
          type: string
      example:
        - id: 3
          contributor: "前川みく"
          body: "みくの初投稿だにゃん"
          createdate: "2018年04月11日 12時00分01秒"
        - id: 4
          contributor: "小日向美穂"
          body: "プロデューサーさん！"
          createdate: "2018年04月12日 12時00分01秒"
    ContributionList:
      type: array
      items:
        $ref: '#/components/schemas/Contribution'
