openapi: 3.0.0
info:
  title: Keijiban
  version: v2
paths:
  /contoribution:
    get:
      summary: 全投稿内容表示
      responses:
        '200':
          description: 過去投稿された内容の一覧
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contributions'
components:
  schemas:
    Contribution:
      required:
        - id
        - contributor
        - body
      properties:
        id:
          type: integer
          format: int32
        contributor:
          type: string
        body:
          type: string
    Contributions:
      type: array
      example:
        - id: 7
          contributor: homahi
          body: Hello developers!
        - id: 38
          contributor: doektak
          body: |
            lorem ipsum
            multi lined message here.
      items:
        $ref: '#/components/schemas/Contribution'
