openapi: 3.0.0
info:
  title: Keijiban
  version: v2
paths:
  /contoribution:
    get:
      summary: 全投稿内容表示
      responses:
        '200':
          description: 過去投稿された内容の一覧
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContributionList'
    post:
      summary: 掲示板投稿
      responses:
        '200':
          description: 新規投稿
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContributionList'

components:
  schemas:
    Contribution:
      required:
        - id
        - contributor
        - body
        - createdAt
      properties:
        id:
          type: integer
          format: int32
        contributor:
          type: string
        body:
          type: string
        createAt:
          type: string
      example:
        - id: 3
          contributor: "前川みく"
          body: "みくの初投稿だにゃん"
          createAt: "2018-04-11T12:00:01"
        - id: 4
          contributor: "小日向美穂"
          body: "プロデューサーさん！"
          createAt: "2018-04-12T12:00:01"
    ContributionList:
      type: array
      items:
        $ref: '#/components/schemas/Contribution'

